name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.2.2
  webview_flutter_android: ^4.9.0
  provider: ^6.1.2
  google_fonts: ^6.2.1 # Cập nhật lên phiên bản mới nhất
  shared_preferences: ^2.3.0
  table_calendar: ^3.2.0
  sqflite: ^2.4.2
  sqflite_common_ffi: any
  path: ^1.9.1
  url_launcher: ^6.1.7
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.0
  crypto: ^3.0.3
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
    - lib/language/lang/language_text.json
    - assets/map.html